language: node_js
sudo: required

node_js:
  - "8"

addons:
  - firefox: "latest"
  - chrome: "stable"

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install:
  - yarn install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 10 # give xvfb some time to start

script:
  - yarn test