language: node_js

node_js:
  - "8"

addons:
  - firefox: "latest"
  - chrome: "stable"

install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn test
